### ISSUE TITLE
Taylor's expansion in the supplement

### ISSUE THREAD

**Issue by SHENGUODONG19951126** [vincent-leguen/PhyDNet#15]
This is great work, and it is very helpful to my current research. I just have a subtle question about Taylor's expansion part in the supplement. I suppose there exist 0th and 1st-degree derivatives in Taylor's expansion, but I don't really find them in the supplement. I am not very familiar with it, could anybody please explain it? Many thanks.

**Comment by vincent-leguen** [comment]
Hi @SHENGUODONG19951126 , thank you for your thorough reading ! I realize that there is indeed a typo in the supplementary 1.2. In the Taylor expansion, the sum should be from i,j=0 and not from i,j=1, so that there exists 0th and 1st order. Thank you for detecting this mistake, I hope it will help you!
Best
Vincent

**Comment by SHENGUODONG19951126** [comment]
Thanks for solving the puzzle. :)
